export const metadata = {
  title: `Portfolio studio`,
  description: "Generated by Nextjs and Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
