import "../globals.css";

export const metadata = {
  title: `Vanathi's Portfolio`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden  bg-[#002f3b] text-white ">
        {/* h-screen */}
        <main>{children}</main>
      </body>
    </html>
  );
}
